name: tf
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - imbalanced-learn==0.14.1
      - joblib==1.5.3
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - numpy==2.2.6
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==26.0
      - pandas==2.3.3
      - pillow==12.1.0
      - protobuf==6.33.4
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sklearn-compat==0.1.5
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - wrapt==2.0.1

